# This file was generated by GoReleaser. DO NOT EDIT.
cask "tektoncd-pac" do
  zsh_completion = "#{staged_path}/_tkn-pac"
  bash_completion = "#{staged_path}/tkn-pac.bash"
  fish_completion = "#{staged_path}/tkn-pac.fish"

  preflight do
    stdout, * = system_command "#{staged_path}/tkn-pac", args: ["completion", "bash"]
    File.write bash_completion, stdout
    stdout, * = system_command "#{staged_path}/tkn-pac", args: ["completion", "zsh"]
    File.write zsh_completion, stdout
    stdout, * = system_command "#{staged_path}/tkn-pac", args: ["completion", "fish"]
    File.write fish_completion, stdout
  end

  binary zsh_completion, target: "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_tkn-pac"
  binary bash_completion, target: "#{HOMEBREW_PREFIX}/etc/bash_completion.d/tkn-pac"
  binary fish_completion, target: "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/tkn-pac.fish"

  name "tektoncd-pac"
  desc "tkn-pac - A command line interface for interacting with Pipelines as Code"
  homepage "https://pipelinesascode.com"
  version "0.39.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tkn-pac"
  depends_on formula: [
      "git",
      "tektoncd-cli",
    ]

  on_macos do
    url "https://github.com/openshift-pipelines/pipelines-as-code/releases/download/v#{version}/tkn-pac_#{version}_darwin_all.zip"
    sha256 "c4ee080ad7705dce823674e13f8dd061b94612ab92cd4f7eebe4d7f407307393"
  end

  on_linux do
    on_intel do
      url "https://github.com/openshift-pipelines/pipelines-as-code/releases/download/v#{version}/tkn-pac_#{version}_linux_x86_64.tar.gz"
      sha256 "b6f11366b8a97498f15572658327086cb5f51640af2156b28b00d3834481f73f"
    end
    on_arm do
      url "https://github.com/openshift-pipelines/pipelines-as-code/releases/download/v#{version}/tkn-pac_#{version}_linux_arm64.tar.gz"
      sha256 "6ef6cdf680ae60d3732628feb3b10aa53b451bf80c95ca05736bc6f0b54bf525"
    end
  end

  # No zap stanza required
end
