# This file was generated by GoReleaser. DO NOT EDIT.
cask "tektoncd-pac" do
  zsh_completion = "#{staged_path}/_tkn-pac"
  bash_completion = "#{staged_path}/tkn-pac.bash"
  fish_completion = "#{staged_path}/tkn-pac.fish"

  preflight do
    stdout, * = system_command "#{staged_path}/tkn-pac", args: ["completion", "bash"]
    File.write bash_completion, stdout
    stdout, * = system_command "#{staged_path}/tkn-pac", args: ["completion", "zsh"]
    File.write zsh_completion, stdout
    stdout, * = system_command "#{staged_path}/tkn-pac", args: ["completion", "fish"]
    File.write fish_completion, stdout
  end

  binary zsh_completion, target: "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_tkn-pac"
  binary bash_completion, target: "#{HOMEBREW_PREFIX}/etc/bash_completion.d/tkn-pac"
  binary fish_completion, target: "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/tkn-pac.fish"

  version "0.42.1"

  on_macos do
    sha256 "efdca1b17048f46aff4037ef64f2aaeb4a81eaee6d93e514efcd2e253c3cb406"
    url "https://github.com/tektoncd/pipelines-as-code/releases/download/v#{version}/tkn-pac_#{version}_darwin_all.zip"
  end

  on_linux do
    on_intel do
      sha256 "fdf7ceb82722f7f424eb8191ff44fa562047856cc7868d443482268c0654a6b3"
      url "https://github.com/tektoncd/pipelines-as-code/releases/download/v#{version}/tkn-pac_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6213fbc0ff7d8aeac1ac891cb54207844de410b4d3d336180cc74fd8f8b29203"
      url "https://github.com/tektoncd/pipelines-as-code/releases/download/v#{version}/tkn-pac_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tektoncd-pac"
  desc "tkn-pac - A command line interface for interacting with Pipelines as Code"
  homepage "https://pipelinesascode.com"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
      "tektoncd-cli",
    ]

  binary "tkn-pac"

  # No zap stanza required

end
